### ISSUE TITLE
Possible issue with FlexibleSUSY in Gambit-2.0

### ISSUE THREAD

**Issue by aseshkdatta** [FlexibleSUSY/FlexibleSUSY#351] opened 2021-07-19 12:14 UTC
Hi,

I am trying to build Gambit-2.0 on a workstation and facing the following error
which seems to be coming from FlexibleSUSY. The detailed message of executing
"make -j24 gambit" is attached herewith.
------------------------------------------------------------------------------------------------------
.........................
.........................
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:86:63: warning: enum constant in boolean context [-Wint-in-bool-context]
     MayLinearVectorize = bool(MightVectorize) && MayLinearize && DstHasDirectAccess
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/eigen3/Eigen/Core:421,
                 from src/rk.hpp:35,
                 from src/basic_rk_integrator.hpp:31,
                 from src/betafunction.hpp:27,
                 from src/lowe.h:31,
                 from src/standard_model_two_scale_low_scale_constraint.hpp:25,
                 from src/standard_model_two_scale_low_scale_constraint.cpp:20:
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:90:50: warning: enum constant in boolean context [-Wint-in-bool-context]
     MaySliceVectorize  = bool(MightVectorize) && bool(DstHasDirectAccess)
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
make[4]: *** [src/standard_model_two_scale_low_scale_constraint.o] Error 1
make[3]: *** [flexiblesusy-prefix/src/flexiblesusy-stamp/flexiblesusy-build] Error 2
make[2]: *** [CMakeFiles/flexiblesusy.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
   Updated Backends/include/gambit/Backends/backend_functor_types.hpp
   Updated Elements/include/gambit/Elements/module_functor_types.hpp
make[3]: warning:  Clock skew detected.  Your build may be incomplete.
[ 12%] Built target module_harvest
make[1]: *** [CMakeFiles/gambit.dir/rule] Error 2
make: *** [gambit] Error 2
------------------------------------------------------------------------------------------------------

The workstation I am working on has the following specifications.
-----------------------------------------------------------------------------------------------
Linux ws2 3.10.0-957.12.1.el7.x86_64 #1 SMP Mon Apr 29 14:59:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

CentOS Linux release 7.6.1810 (Core) 
[asesh@ws2 build]$^C

Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz      (48 computing cores)
Memory 96 GB
---------------------------------------------------------------------------------------------

Could you you please shed light on the issue.

Thanks and regards.
Asesh
[make-gambit-ws2-1.txt](https://github.com/FlexibleSUSY/FlexibleSUSY/files/6840652/make-gambit-ws2-1.txt)

**Comment by Expander** [comment] 2021-07-19 12:51
Dear @aseshkdatta 

the line you've printed is just a warning and is not the error. From your output file I see the following error message:
~~~
In file included from src/standard_model_two_scale_low_scale_constraint.cpp:26:
src/minimizer.hpp: In member function ‘const gsl_multimin_fminimizer_type* flexiblesusy::Minimizer<dimension>::solver_type_to_gsl_pointer() const’:
src/minimizer.hpp:223:33: error: ‘gsl_multimin_fminimizer_nmsimplex2’ was not declared in this scope
    case GSLSimplex2    : return gsl_multimin_fminimizer_nmsimplex2;
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/minimizer.hpp:223:33: note: suggested alternative: ‘gsl_multimin_fminimizer_nmsimplex’
    case GSLSimplex2    : return gsl_multimin_fminimizer_nmsimplex2;
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                 gsl_multimin_fminimizer_nmsimplex
src/minimizer.hpp:224:33: error: ‘gsl_multimin_fminimizer_nmsimplex2rand’ was not declared in this scope
    case GSLSimplex2Rand: return gsl_multimin_fminimizer_nmsimplex2rand;
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/minimizer.hpp:224:33: note: suggested alternative: ‘gsl_multimin_fminimizer_nmsimplex’
    case GSLSimplex2Rand: return gsl_multimin_fminimizer_nmsimplex2rand;
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                 gsl_multimin_fminimizer_nmsimplex
~~~
The file `src/minimizer.hpp` that uses this type includes the header:
~~~.cpp
#include "gsl_multimin_fminimizer.hpp"
~~~
which includes
~~~.cpp
#include <gsl/`>
~~~
It may be that there is some change within the GSL headers that causes this error? I think `gsl_multimin.h` should have properly declared `gsl_multimin_fminimizer_nmsimplex2`.

**Comment by Expander** [comment] 2021-07-19 12:55
Could you please print the GSL version that you're using?
~~~
gsl-config --version
~~~

**Comment by aseshkdatta** [comment] 2021-07-19 13:19
Thanks a lot for your observation. The results is as follows.
------------------------------------------------------------------------------
[asesh@ws2 build]$gsl-config --version
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
1.10
[asesh@ws2 build]$
--------------------------------------------------------

Looks like there is some definite issues with gsl.
Looking forward to your comments and suggestions.

Regards.
Asesh

**Comment by aseshkdatta** [comment] 2021-07-19 13:21
Thanks a lot for your observations. The result is as follows.
------------------------------------------------------------------------------
[asesh@ws2 build]$gsl-config --version
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
1.10
[asesh@ws2 build]$
---------------------------------------------------------

Looks like there are some definite issues with gsl.
Looking forward to your comments and suggestions.

Regards.
Asesh

**Comment by Expander** [comment] 2021-07-19 13:24
Hi @aseshkdatta ,

ok, the issue is that your version of GSL is too old. I've just looked into the source code of GSL 1.10 and the symbol `gsl_multimin_fminimizer_nmsimplex2` is not defined there. So, it must have been introduced in a later version. Please use a newer version of GSL and the issue should be fixed. :)

Best regards
Alex

**Comment by Expander** [comment] 2021-07-19 13:32
I've added a check in the `configure` file to require at least GSL 2.0, where `gsl_multimin_fminimizer_nmsimplex2` is available, see commit cc5ddd63d2fb17.

**Closed by Expander** 2021-07-19 13:32 UTC

**Comment by aseshkdatta** [comment] 2021-07-19 13:34
Thanks a lot, Alex.
I'll soon work with our admin on this issue and will keep you posted.

Regards.
Asesh

**Comment by Expander** [comment] 2021-07-19 13:38
Hi @aseshkdatta 

no worries!

In principle you can install GSL into your home directory via
~~~.sh
./configure --prefix=${HOME}/gsl
make
make check
make install
~~~
Afterwards you can tell FlexilbeSUSY's `configure` script to use your privately installed GSL version:
~~~.sh
./configure --with-gsl-config=${HOME}/gsl/bin/gsl-config
~~~
or similar.

**Comment by pathron** [comment] 2021-07-19 13:44
Hi @aseshkdatta,

Just to add (with my gambit cap on) that if you were not intending to use gambit with a FlexibleSUSY spectrum generator then you could try to avoid the issue altogether.  You  could set 
-DBUILD_FS_MODELS=“” 
during the cmake step of gambit and then gambit should not try to compile any FS code.   However this will not help you of you wanted to use the FS spectrum generators, to eg get the MSSM mass spectrum.

**Comment by Expander** [comment] 2021-07-19 13:50
But of course, using something else instead of FlexibleSUSY would not be desirable!  :D

**Comment by aseshkdatta** [comment] 2021-07-19 13:52
Thanks again, Alex.
Yes, exactly:) I would like to keep FS in!

Let me try out your prescription  first.

Cheers.
Asesh
