### ISSUE TITLE
function returning number of active quark flavours

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#302] opened 2021-02-25 12:20 UTC
There's sort of a duplication in decays. I've introduced a function
```cpp
unsigned int number_of_active_flavours(softsusy::QedQcd const& qedqcd, double m) noexcept    
{    
   if (m < qedqcd.displayMbMb()) {    
      return 4;    
   } else if (m < qedqcd.displayPoleMt()) {    
      return 5;    
   } else {    
      return 6;    
   }    
}    
```
This is similar to a private function `flavours` in `QedQcd`
```cpp
//  Active flavours at energy mu    
int QedQcd::flavours(double mu) const {    
  int k = 0;    
  // if (mu > mf(mTop - 1)) k++;    
  if (mu > mf(mCharm - 1)) { k++; }    
  if (mu > mf(mUp - 1)) { k++; }    
  if (mu > mf(mDown - 1)) { k++; }    
  if (mu > mf(mBottom - 1)) { k++; }    
  if (mu > mf(mStrange - 1)) { k++; }    
  return k;    
} 
```
Should we merge them?

**Comment by uukhas** [comment] 2021-02-25 12:25
Do you mean to keep (making public via some interface) `flavours` of `QedQcd`?

**Comment by wkotlarski** [comment] 2021-02-25 12:26
Make public and remove the one from decays.

**Comment by uukhas** [comment] 2021-02-25 12:28
This sounds suitable for me and I do not see any problems to make it public, because this function is not destructive (does not change any internal variables).

**Comment by Expander** [comment] 2021-02-25 12:30
I'd also vote for making `flavours` public and use this one.

**Comment by wkotlarski** [comment] 2021-02-25 12:44
The only problem is that this function returns 5 for `qedqcd.flavours(200.)`.

**Comment by Expander** [comment] 2021-02-25 12:47
Oh, you're right. The reason is that `QedQcd` returns only SM(5) couplings, by convention.

**Comment by Expander** [comment] 2021-02-25 12:49
I would not change the `flavours` function then. Instead, you might write a new public function which returns the "true" number of flavours. The issue is to find a proper name for the function. :)

**Comment by pathron** [comment] 2021-02-25 13:19
Is there a reason the top quark needs to be commented out at the top of flavours though? Is it ever needed to be 5 above the top quark mass?

**Comment by Expander** [comment] 2021-02-25 13:29
The reason is that `QedQcd` is required to return the SM(5) couplings, not SM(6) couplings.

**Comment by pathron** [comment] 2021-02-25 13:46
Yeah sorry I get that, but I am not sure it makes sense to use `QedQcd` above the top quark mass, so I am asking if we do?  And if we were using it above mt do we would really want SM(5) couplings then?

**Comment by Expander** [comment] 2021-02-25 13:50
Yes, it may happen that we use it above mt, for example if the user chooses to extract the couplings at some arbitrary scale that may be > mt.

Formally, the loop calculations are still correct at the respective loop order, because they assume SM(5) to come out of `QedQcd` and use it accordingly (adding threshold for the top, for example).

**Comment by pathron** [comment] 2021-02-25 14:02
Ah right, of course that’s possible.  It would be better if they did not do that though, and if they did we could have a different matching procedure.  

Anyway this is a tangent.  I think Wojtek closed the thread because he already has his function - number_of_active_flavours, shown at the top.

**Comment by wkotlarski** [comment] 2021-02-25 14:17
Wojtek did not close the thread. Should Wojtek do that?

**Comment by pathron** [comment] 2021-02-26 01:21
Haha sorry I was confused by Alex closing and then reopening it and somehow assumed you had done the closing.

I guess it can be closed though, unless we want to discuss your number_of_active_flavours function?

**Comment by Expander** [comment] 2021-02-26 07:22
I think it cannot be closed yet, because Wojtek needs a function that returns the number of quark flavours in the SM, up to (including) 6.

**Comment by wkotlarski** [comment] 2021-02-26 14:54
I have my own function. Dylan also did the same. So from my point of view we can leave it like that.

**Comment by Expander** [comment] 2021-02-26 15:24
Sorry, do you mean to not change anything? I thought changing the code was the proposal.  :)

**Comment by wkotlarski** [comment] 2021-02-26 15:28
Yes. But since the functions are suppose to be different (one returns numbers < 6 and other <= 6) we can leave things as they are right now.

**Comment by Expander** [comment] 2021-02-26 15:38
Ok, I see, sorry for the confusion.

**Closed** 2021-02-26 15:40 UTC
Labels: question
