### ISSUE TITLE
Variable @MODEL_SPECIFIC_MODULES@ not set during compilation on version > 2.5.0

### ISSUE THREAD

**Issue by michelelucente** [FlexibleSUSY/FlexibleSUSY#594] opened 2024-01-27 22:45 UTC
Hi, 

I have an error while compiling on FlexibleSUSY > 2.5.0. It seems that the variable `@MODEL_SPECIFIC_MODULES@` is not assigned by the `configure` script, so I have the following error while compiling:
```
(PT) ➜  FlexibleSUSY git:(v2.7.1) ✗ make -j8
Makefile:188: model_specific/@MODEL_SPECIFIC_MODULES@/module.mk: No such file or directory
Building models/THDMIISNMSSMBCsimple/00_DELETE_ME_TO_RERUN_METACODE
Mathematica 14.0.0 Kernel for Mac OS X ARM (64-bit)
Copyright 1988-2023 Wolfram Research, Inc.
make: *** No rule to make target `model_specific/@MODEL_SPECIFIC_MODULES@/module.mk'.  Stop.
make: *** Waiting for unfinished jobs....
```

I tried different versions and the most recent one that does not show the problem is 2.5.0
```
(PT) ➜  FlexibleSUSY git:(v2.5.0) ✗ make -j8
Building models/THDMIISNMSSMBCsimple/00_DELETE_ME_TO_RERUN_METACODE
Mathematica 14.0.0 Kernel for Mac OS X ARM (64-bit)
Copyright 1988-2023 Wolfram Research, Inc.

In[1]:= SARAH 4.15.2
```

I indeed notice a different output while calling `configure`, for v2.5.0:
```
(PT) ➜  FlexibleSUSY git:(v2.5.0) ✗ ./configure --with-models=THDMIISNMSSMBCsimple  --with-math-cmd=WolframKernel --with-cxx=clang++
Checking for RGE solvers ... ok (two_scale semi_analytic)
Checking for Mathematica kernel WolframKernel ... found /Applications/Mathematica.app/Contents/MacOS/WolframKernel
Checking for Mathematica version >= 7 ... ok (version 14. for MacOSX-ARM64 in /Applications/Mathematica.app/Contents)
Checking for SARAH installation ... ok (version 4.15.2)
Checking for FeynArts installation ... ok (not installed)
Checking for FormCalc installation ... ok (not installed)
Checking for models ... ok (THDMIISNMSSMBCsimple)
Checking model makefiles
   Updating model-specific modules in models/THDMIISNMSSMBCsimple/module.mk ... (SM)
```

there is the line `Updating model-specific modules in models/THDMIISNMSSMBCsimple/module.mk ... (SM)`, while for versions above there isn't:
```
(PT) ➜  FlexibleSUSY git:(v2.7.1) ✗ ./configure --with-models=THDMIISNMSSMBCsimple  --with-math-cmd=WolframKernel --with-cxx=clang++                         
Checking for RGE solvers ... ok (two_scale semi_analytic)
Checking for Mathematica kernel WolframKernel ... found /Applications/Mathematica.app/Contents/MacOS/WolframKernel
Checking for Mathematica version >= 11.0 ... ok (version 14. for MacOSX-ARM64 in /Applications/Mathematica.app/Contents)
Checking for SARAH installation ... ok (version 4.15.2)
Checking for FeynArts installation ... ok (not installed)
Checking for FormCalc installation ... ok (not installed)
Checking for models ... ok (THDMIISNMSSMBCsimple)
Checking model makefiles
Checking model files for required third party libraries
```

Thank you!

**Comment by Expander** [comment] 2024-01-27 22:50
Hi @michelelucente ,

I stumbled upon a similar issue a few weeks ago. For me the problem was solved by ensuring that I always run `./createmodel` first and then `./configure` (and always both and in this order). Can you please check if this works for you as well?

Best
Alex

**Comment by michelelucente** [comment] 2024-01-27 22:57
Hi @Expander, I confirm that I always run `./createmodel` and then `./configure`.

I paste here the full chain of output

```
(PT) ➜  FlexibleSUSY git:(v2.7.1) ✗ ./createmodel --name=THDMIISNMSSMBCsimple  --with-math-cmd=WolframKernel --force                
Searching for THDMIISNMSSMBCsimple model file ... found model_files/THDMIISNMSSMBCsimple/FlexibleSUSY.m.in
Searching for default SARAH model in model_files/THDMIISNMSSMBCsimple/FlexibleSUSY.m.in ... found "THDMS";
Checking SARAH model THDMS ... ok
Creating model THDMIISNMSSMBCsimple (SARAH model: THDMS)
  Creating Makefile module models/THDMIISNMSSMBCsimple/module.mk ... done
  Creating start script models/THDMIISNMSSMBCsimple/start.m ... done
  Creating FlexibleSUSY model file models/THDMIISNMSSMBCsimple/FlexibleSUSY.m ... touch: out of range or illegal time specification: YYYY-MM-DDThh:mm:SS[.frac][tz]
done
  Creating SLHA input file models/THDMIISNMSSMBCsimple/LesHouches.in.THDMIISNMSSMBCsimple.BM1 ... done
  Creating SLHA input file models/THDMIISNMSSMBCsimple/LesHouches.in.THDMII ... done
```

```
(PT) ➜  FlexibleSUSY git:(v2.7.1) ✗ ./configure --with-models=THDMIISNMSSMBCsimple  --with-math-cmd=WolframKernel --with-cxx=clang++
Checking for RGE solvers ... ok (two_scale semi_analytic)
Checking for Mathematica kernel WolframKernel ... found /Applications/Mathematica.app/Contents/MacOS/WolframKernel
Checking for Mathematica version >= 11.0 ... ok (version 14. for MacOSX-ARM64 in /Applications/Mathematica.app/Contents)
Checking for SARAH installation ... ok (version 4.15.2)
Checking for FeynArts installation ... ok (not installed)
Checking for FormCalc installation ... ok (not installed)
Checking for models ... ok (THDMIISNMSSMBCsimple)
Checking model makefiles
Checking model files for required third party libraries
Checking for C++ compiler clang++ ... found /usr/bin/clang++
Checking for type of C++ compiler clang++ ... Clang
Checking for clang++ compiler version >= 3.8.1 ... ok (version 15.0.0)
Checking for Fortran compiler gfortran ... found /usr/local/bin/gfortran
Checking for LibraryLink ... yes
Checking for WolframLibrary.h ... found in /Applications/Mathematica.app/Contents/SystemFiles/IncludeFiles/C
Checking for mathlink.h ... found in /Applications/Mathematica.app/Contents/SystemFiles/Links/MathLink/DeveloperKit/MacOSX-ARM64/CompilerAdditions
Checking for libMLi4 ... found in /Applications/Mathematica.app/Contents/SystemFiles/Links/MathLink/DeveloperKit/MacOSX-ARM64/CompilerAdditions
Checking for boost/version.hpp ... found in /usr/local/include
Checking for boost version >= 1.37.0 ... ok (version 1.81.0)
Checking for boost/test/unit_test.hpp ... found in /usr/local/include
Checking for libboost_unit_test_framework libboost_unit_test_framework-mt ... found in /usr/local/lib
Checking for Eigen/Core ... found in /usr/local/include/eigen3
Checking for eigen version ... unknown
Warning: could not determine eigen version because
   compilation or execution of the eigen test program failed.
Checking for libgfortran ... found in /usr/local/lib/gcc/aarch64-apple-darwin22.4.0/13.0.1/../../../
Checking for GSL configuration gsl-config ... found /Users/michele/miniconda3/envs/PT/bin/gsl-config (version 2.7.1)
Checking for gm2calc/gm2_version.h ... not found in 
Checking for himalaya/version.hpp ... not found in 
Checking for boost/numeric/odeint.hpp ... found in /usr/local/include
Checking for boost/numeric/odeint/algebra/algebra_dispatcher.hpp ... found in /usr/local/include
Checking for boost/numeric/odeint/algebra/vector_space_algebra.hpp ... found in /usr/local/include
Checking for boost/numeric/odeint/external/eigen/eigen_algebra_dispatcher.hpp ... found in /usr/local/include
Checking for boost/numeric/odeint/external/eigen/eigen_resize.hpp ... found in /usr/local/include
Checking for boost/numeric/odeint/integrate/integrate_adaptive.hpp ... found in /usr/local/include
Checking for boost/numeric/odeint/stepper/generation.hpp ... found in /usr/local/include
Checking for boost/numeric/odeint/stepper/runge_kutta_fehlberg78.hpp ... found in /usr/local/include
Checking for sqlite3.h ... not found in  ::/usr/include:/usr/local/include
Warning: sqlite.h not found in  ::/usr/include:/usr/local/include.
   Support for SQLite will be is disabled.
Checking for tsil.h ... not found in  ::/usr/include:/usr/local/include
Checking for build static library command ar cru ... found /usr/bin/ar
Checking for build shared library command clang++ -shared -o ... found /usr/bin/clang++
Checking for random number generator ... ok
Checking for std::thread ... ok
Checking for libpthread ... found in /usr/local/lib
Disabling GM2Calc
Disabling Himalaya
Disabling sqlite
Disabling TSIL
```

```
(PT) ➜  FlexibleSUSY git:(v2.7.1) ✗ make -j8
Makefile:188: model_specific/@MODEL_SPECIFIC_MODULES@/module.mk: No such file or directory
make: *** No rule to make target `model_specific/@MODEL_SPECIFIC_MODULES@/module.mk'.  Stop.
make: *** Waiting for unfinished jobs....
```

**Comment by michelelucente** [comment] 2024-01-28 01:34
Hi @Expander , following your comment I experimented a bit, and I found a workaround: I need to call **2 times** the `./configure` command.

The first time there is nothing in the output after `Checking model makefiles`, while the second time it appears `Updating model-specific modules in models/THDMIISNMSSMBCsimple/module.mk ... (SM)`

I am still unable to run the spectrum generator, but now the compilation ends and I have the `./run_THDMIISNMSSMBCsimple.x` file in the folder, so I think this is a different issue.

**Comment by pathron** [comment] 2024-01-28 03:27
@michelelucente what OS are you using?  Its macOS?

I think you are trying to build the FS model from PhaseTracer which has NMSSM boundary conditions matched onto the two-Higgs doublet model plus singlet?   Is this to work around some problem you have building the FS version for that in PhaseTracer?  I just checked this model_file works me with 2.7.1, but there may also be some other compatibility issues as well that would affect you using it directly in PT for this example which we give for adding a potential with FS code for the masses so let me know if you also have problems there (the FS version we have there could use an update really but it was just done as an example).

**Comment by Expander** [comment] 2024-01-28 08:40
I think the issue is within the function `update_module_mk` in `configure`: It has some built-in wait time, which I have no idea where it comes from. I'll open an issue to discuss and fix it.

@michelelucente Thanks a lot for reporting this issue! I thing you're by far not the only one who sees this problem.

**Comment by Expander** [comment] 2024-01-28 17:55
Fixed in #595

**Closed** 2024-01-28 17:55 UTC

**Comment by michelelucente** [comment] 2024-01-29 15:17
Hi @pathron,

Indeed what I am trying to build is the FS model from PhaseTracer. I am building it in FS because I need to pass additional flags which I was not able to do with the automated script; for instance on my machine the Mathematica kernel is named `WolframKernel`, so I need the flag `--with-math-cmd=WolframKernel` otherwise FS looks for a kernel with the name `math`.

A very useful addition would be to be able to define FS flags in https://github.com/PhaseTracer/PhaseTracer/blob/64eadae863419f6f994e655b3608590fed6094af/cmake/FindFlexibleSUSY.cmake#L34

Also, is there a specific reason why the cmake script uses FS v2.4.2?

Thank you!

**Comment by pathron** [comment] 2024-01-30 03:35
@michelelucente Yes I think the reason I fixed the version in cmake is because in the phase tracer interface https://github.com/PhaseTracer/PhaseTracer/blob/64eadae863419f6f994e655b3608590fed6094af/example/THDMIISNMSSMBCsimple/THDMIISNMSSMBCsimple.hpp we are not just using standard input and output of FS but really things that will be seen as "internal" in FS and therefore could change.   That is why I said above that there *may* be compatibility issues.   If you are writing a new model you can avoid this entire;y bu just making sure you use routines from the same FS vesrion you run (everything we need should be found in <modelname>_mass_eigenstates.hpp/.cpp ). 

 Ideally we would use FS to actually generate the effective potential class for PT from FlexibleSUSY, but I haven't been able to persuade someone to do that yet.   So for now we just offer this as an example to use FS to get the field dependent masses into the effective potential, which can be useful if there are are a lot of masses you need to add in your particular model and this requires calling routines in FS for getting the mass matrices etc. It does unfortunately require some understanding of FS on the users part though.

Adding the flags to cmake is a good idea,  I will look into that.  A temporary solution for you if you want to just use this example is  to add the ones you need directly there where the ./configure command is called in that cmake file.
