### ISSUE TITLE
Build stuck with the warning related to Flexiblesusy

### ISSUE THREAD

**Issue by Aqsa-physics** [FlexibleSUSY/FlexibleSUSY#261] opened 2020-08-05 18:30 UTC
I am building a physics software "gambit" and at the last step of

`make -jn gambit
`
I am getting the following warning over and over again and the build process is not proceeding forward. This is the warning I am getting regarding flexiblesusy:

`In file included from /usr/include/c++/7/cassert:44:0, from src/gsl_utils.hpp:26, from src/root_finder.hpp:33, from src/standard_model.cpp:33: src/gsl_utils.hpp: In instantiation of ‘void flexiblesusy::copy(const Eigen::DenseBase<Derived>&, gsl_vector*) [with Derived = Eigen::Matrix<double, 1, 1, 0, 1, 1>]’: src/root_finder.hpp:223:8: required from ‘static int flexiblesusy::Root_finder<dimension>::gsl_function(const gsl_vector*, void*, gsl_vector*) [with long unsigned int dimension = 1]’ src/root_finder.hpp:139:27: required from ‘int flexiblesusy::Root_finder<dimension>::find_root(const Vector_t&) [with long unsigned int dimension = 1; flexiblesusy::Root_finder<dimension>::Vector_t = Eigen::Matrix<double, 1, 1, 0, 1, 1>]’ src/root_finder.hpp:263:21: required from ‘int flexiblesusy::Root_finder<dimension>::solve(const VectorXd&) [with long unsigned int dimension = 1; Eigen::VectorXd = Eigen::Matrix<double, -1, 1>]’ src/standard_model.cpp:4593:1: required from here src/gsl_utils.hpp:97:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare] assert(dim == dst->size);
`

This is where my build is stuck with the same above warning repeated over and over.

Any help will be useful. Thank you.

**Comment by pathron** [comment] 2020-08-05 18:51
I started replying to this report here: https://github.com/patscott/gambit_1.2/issues/4

**Comment by pathron** [comment] 2020-08-11 08:22
I'm closing this here because I believe further discussion in https://github.com/patscott/gambit_1.4/issues/3 confirmed that there was at least no problem with FS and it was just the slow gambit/FS  build making  Aqsa-physics suspicious.

**Closed by pathron** 2020-08-11 08:22 UTC

**Comment by Aqsa-physics** [comment] 2020-08-14 15:27
Yes. Thank you very much... 
Further discussions have been carried on the following thread
https://github.com/patscott/gambit_1.4/issues/3
Thanks for your help.
